### ISSUE TITLE
Product name is "Particle Photon", not "Proton"

### ISSUE THREAD

**Issue by mikewop** [4dsystems/ViSi-Genie-Particle-Library#1]
Thanks for creating this library!
I think the correct product name is "Particle Photon", the readme file mentions "Proton" several times , but I do not think that a valid product on their website.
Would be easier to find for people looking for the library for interfacing their particle Photon with 4D systems displays.

**Comment by 4dsystems** [comment]
Good spotting, thank you. This will be updated in the readme asap.
